TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) 	main.o \
			f3d_led.o \
			f3d_uart.o \
			f3d_usr_btn.o \
			f3d_systick.o \
			glcdfont.o \
			stm32f30x_rcc.o \
			stm32f30x_gpio.o \
			stm32f30x_usart.o \
			stm32f30x_spi.o \
			stm32f30x_i2c.o \
			stm32f30x_rtc.o \
			stm32f30x_tim.o \
			stm32f30x_pwr.o \
			newlib_stubs.o
# include common make file

include $(TEMPLATEROOT)/Makefile.common


